//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeHuoLeBao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyEntities : DbContext
    {
        public HappyEntities()
            : base("name=HappyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dl_basic_users> dl_basic_users { get; set; }
        public DbSet<sys_function> sys_function { get; set; }
        public DbSet<sys_role> sys_role { get; set; }
        public DbSet<sys_role_function> sys_role_function { get; set; }
        public DbSet<sys_user_role> sys_user_role { get; set; }
        public DbSet<t_f_news> t_f_news { get; set; }
        public DbSet<t_f_park> t_f_park { get; set; }
        public DbSet<t_f_recruit> t_f_recruit { get; set; }
    }
}
