//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeHuoLeBao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_f_recruit
    {
        public decimal recruitid { get; set; }
        public string re_name { get; set; }
        public string re_type { get; set; }
        public string re_money { get; set; }
        public string re_require { get; set; }
        public Nullable<bool> isDel { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
    }
}
